import { Property } from '../services/propertyService';

export const mockProperties: Property[] = [
    {
        id: '1',
        title: 'Modern Apartment in Semarang',
        description: 'Beautiful 2-bedroom apartment with city view',
        address: 'Jl. Pemuda No. 123',
        city: 'Semarang',
        state: 'Central Java',
        country: 'Indonesia',
        zipCode: '50132',
        latitude: -6.9667,
        longitude: 110.4167,
        price: 2500000,
        currencyCode: 'IDR',
        propertyTypeId: '1',
        bedrooms: 2,
        bathrooms: 1,
        areaSqm: 45,
        furnished: true,
        isAvailable: true,
        status: 'ACTIVE' as const,
        images: ['https://via.placeholder.com/300x200'],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '2',
        title: 'Cozy House in Semarang Barat',
        description: 'Family-friendly house with garden',
        address: 'Jl. Gajah Mada No. 456',
        city: 'Semarang',
        state: 'Central Java',
        country: 'Indonesia',
        zipCode: '50149',
        latitude: -6.9833,
        longitude: 110.4000,
        price: 4000000,
        currencyCode: 'IDR',
        propertyTypeId: '2',
        bedrooms: 3,
        bathrooms: 2,
        areaSqm: 80,
        furnished: false,
        isAvailable: true,
        status: 'ACTIVE' as const,
        images: ['https://via.placeholder.com/300x200'],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '3',
        title: 'Studio Apartment Near UNDIP',
        description: 'Perfect for students, close to university',
        address: 'Jl. Prof. Soedarto No. 789',
        city: 'Semarang',
        state: 'Central Java',
        country: 'Indonesia',
        zipCode: '50275',
        latitude: -7.0500,
        longitude: 110.4333,
        price: 1800000,
        currencyCode: 'IDR',
        propertyTypeId: '1',
        bedrooms: 1,
        bathrooms: 1,
        areaSqm: 25,
        furnished: true,
        isAvailable: true,
        status: 'ACTIVE' as const,
        images: ['https://via.placeholder.com/300x200'],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
];

export const mockPropertiesResponse = {
    success: true,
    data: {
        properties: mockProperties,
        pagination: {
            page: 1,
            limit: 10,
            total: mockProperties.length,
            totalPages: 1,
        },
    },
};
